embed.embed_type_settings.embed_media:
  type: mapping
  label: 'Schema for the media embed type'
  mapping:
    media_types:
      type: sequence
      label: 'Media types'
      sequence:
        type: string
        label: 'The media type'
    entity_browser:
      type: string
      label: 'Entity browser'
    entity_browser_settings:
      type: mapping
      label: 'Entity browser settings'
      mapping:
        display_review:
          type: boolean
          label: 'Display review step'

oe_media_embed.settings:
  type: config_object
  label: 'Configuration for the media embed module.'
  mapping:
    resource_base_url:
      type: uri
      label: 'Base path for the oEmbed resource URL'
    service_url:
      type: uri
      label: 'oEmbed service URL'
