embed.embed_type_settings.embed_media:
  type: mapping
  label: 'Schema for the media embed type'
  mapping:
    media_types:
      type: sequence
      label: 'Media types'
      sequence:
        type: string
        label: 'The media type'

oe_media_embed.settings:
  type: config_object
  label: 'Configuration for the media embed module.'
  mapping:
    resource_base_url:
      type: uri
      label: 'Base path for the oEmbed resource URL'
    service_url:
      type: uri
      label: 'oEmbed service URL'
