field.value.oe_media_circabc_circabc_reference:
  type: mapping
  label: Default value
  mapping:
    uuid:
      type: uuid
      label: UUID
    size:
      type: integer
      label: Size
    mime:
      type: string
      label: Mime type
    filename:
      type: string
      label: File name

field.widget.settings.oe_media_circabc_default_widget:
  type: field.widget.settings.string_textfield
