views.filter.avportal_text_search:
  type: views.filter.string
  label: 'AV Portal Search'

entity_browser.browser.widget.avportal_search:
  type: entity_browser.browser.widget.view
  label: 'AV Portal widget configuration'

entity_browser.browser.widget.av_portal_upload_link:
  type: mapping
  label: 'Widget configuration'
  mapping:
    submit_text:
      type: string
      label: 'Submit button text'

